name: JustEvents
version: ${project.version}
main: dev.just.justevents.Main
api-version: 1.21
author: justCoding
commands:
  allowplayer:
    description: Allow a player to connect to a project
  build:
    description: Allows the player to build in the lobby
  ban:
    description: Ban a player from the server